# Generated by Django 5.2 on 2025-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookRating', models.FloatField(max_length=50)),
                ('BookPublish', models.IntegerField()),
                ('cover_image', models.ImageField(upload_to='static/Userview/')),
                ('BookAuthor', models.CharField(max_length=100)),
                ('summary', models.TextField(max_length=200)),
            ],
        ),
    ]
