# Generated by Django 5.2 on 2025-05-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='BookPublish',
        ),
        migrations.RemoveField(
            model_name='management',
            name='summary',
        ),
        migrations.AddField(
            model_name='management',
            name='Booktitle',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='management',
            name='cover_image',
            field=models.ImageField(default='', upload_to='static/Userview/'),
        ),
    ]
