# Generated by Django 5.2 on 2025-06-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_cart_book_remove_cart_user_cart_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='Bookprice',
            field=models.FloatField(default=1.0),
        ),
    ]
